services:
  ambient-llm:
    container_name: ambient-llm
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ../academic:/app/academic

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

volumes:
  ollama_data: